### ISSUE TITLE
Looking for production implementation

### ISSUE THREAD

**Issue by ealsur** [richorama/AzureStorageExtensions#1]
Hi!
I was looking for Graph storing alternatives on Azure for a X-IsInterestedIn-Y scenario and wondered if your extension has been used before on a production environtment.

Right now my alternative is DocumentDB but your approach sounds a bit more suitable.

This is for a product not yet created, so it's not something that involves migrations of data of anything like that.

**Comment by richorama** [comment]
Hi, thanks for your interest!

The project was started as a bit of an experiment. I don't know of anyone using it in production.

It's a bit out of date, but could easily be upgraded to the latest storage SDK.

The graph works by storing each 'triple' (i.e. subject, predicate, object) three times, to provide fast query times (i.e. you can query by any of the dimensions, and the data is indexed) the downside is that the data is stored in three different partitions, and there is no transaction across these partitions. 

You can see the code that does the write here:

https://github.com/richorama/AzureStorageExtensions/blob/master/AzureGraphStore/Graph.cs#L48-L70

Therefore, in the event of one of these writes failing (even with a retry policy) you may get a data inconsistency. For some applications this might not matter, or you may think that the risk is low enough to be acceptable. There are of course ways of mitigating this risk, like channelling writes through a queue (in a CQRS style) to make sure all the data gets written eventually.

I just want to make it really clear that this might happen.

It would be interesting to see if service fabric might provide a better basis for building a triple store.

**Comment by richorama** [comment]
Happy to update the project you're interested in using it...

**Comment by ealsur** [comment]
Thanks for the taking the time to write @richorama ! 
I've used it on the past on small projects and works wonders. This time, it's for a bigger project and was unsure if you had ever tested it or heard of anyone trying it on high volumes of data.

In my case, everything would be behind an Azure Storage Queue processing atomic operations, in case of a failure, it would just retry eventually on the queue, so I guess I'm covered there.

If you don't mind, I'm gonna give it a spin with ASP.NET Core RC2 and Net Framework 461, if I bump on anything and I can solve it, I'll gladly do some PRs for you to evaluate :)

**Comment by richorama** [comment]
The library is just a thin layer on top of table storage, so for scalability you should be ok :¬)

I look forward to the PRs, if you have any questions let me know!

I'll close this issue for now. Feel free to open more if there's anything else...
